package game

// 任务相关
const (
	TASK_TYPE_PLAYER_LEVEL              = 1   // 玩家等级
	TASK_TYPE_CRYSTAL_FIGHT             = 2   // 法阵战力
	TASK_TYPE_GET_HERO                  = 11  // 获得英雄
	TASK_TYPE_BIGGEST_LEVEL             = 12  // 英雄到达指定顶级
	TASK_TYPE_LEVEL_UP_COUNT            = 13  // 英雄升级次数
	TASK_TYPE_STAR_UP_COUNT             = 14  // 英雄大圣堂升阶
	TASK_TYPE_HAVE_HERO                 = 15  // 拥有指定条件英雄
	TASK_TYPE_GET_HOOK_AWARD            = 21  // 领取挂机宝箱次数
	TASK_TYPE_GET_HOOK_FAST_AWARD       = 22  // 领取挂机快速奖励次数
	TASK_TYPE_GET_HOOK_GET_ITEM         = 23  // 领取挂机物品数量
	TASK_TYPE_EQUIP_LEVEL_UP            = 31  // 装备强化
	TASK_TYPE_HAVE_EQUIP                = 32  // 拥有装备
	TASK_TYPE_FINISH_PASS               = 41  // 完成普通关卡
	TASK_TYPE_FINISH_MAIN_PASS          = 42  // 完成主线关卡
	TASK_TYPE_FINISH_CHAPTER            = 43  // 完成章节
	TASK_TYPE_MONTH_STATE               = 50  // 月卡任务
	TASK_TYPE_ARENA_COUNT               = 51  // 竞技场胜利次数
	TASK_TYPE_ARENA_POINT               = 52  // 竞技场积分
	TASK_TYPE_SPECIAL_ARENA_CLASS       = 53  // 高阶竞技场段位
	TASK_TYPE_PIT_PASS                  = 61  // 通过迷宫
	TASK_TYPE_PIT_KILL                  = 62  // 迷宫击杀
	TASK_TYPE_PIT_KILL_PLAYER           = 63  // 迷宫击杀玩家
	TASK_TYPE_RESONANCE_CRYSTAL_COUNT   = 71  // 共鸣水晶开启槽位
	TASK_TYPE_RESONANCE_CRYSTAL_LEVEL   = 72  // 共鸣水晶提升的等级
	TASK_TYPE_RESONANCE_CRYSTAL_SET     = 73  // 共鸣水晶提升的等级
	TASK_TYPE_WOTER_LEVEL               = 81  // 王座塔层级
	TASK_TYPE_WOTER_COUNT               = 82  // 王座塔次数
	TASK_TYPE_CAMP_WOTER_LEVEL          = 83  // 种族塔层数
	TASK_TYPE_ONE_CAMP_TOWER_LEVEL      = 84  // 某一种族塔层数
	TASK_TYPE_UNION_HUNT_COUNT          = 91  // 公会狩猎参与次数
	TASK_TYPE_REWARD_TASK_SET           = 101 // 悬赏接受
	TASK_TYPE_REWARD_TASK_GET           = 102 // 悬赏完成
	TASK_TYPE_REWARD_LEVLE              = 103 // 悬赏栏等级
	TASK_TYPE_FRIEND_POINT_COUNT        = 111 // 友情点次数
	TASK_TYPE_FRIEND_POINT              = 112 // 友情点数
	TASK_TYPE_SUMMON_HEROS              = 121 // 召唤英雄
	TASK_TYPE_SHOP_BUY_COUNT            = 122 // 商店购买次数
	TASK_TYPE_ADD_LIVENESS              = 123 // 增加活跃度
	TASK_TYPE_JOIN_UNION                = 124 // 加入公会
	TASK_TYPE_LOGIN_TOTAL_COUNT         = 125 // 登录次数
	TASK_TYPE_REG_TOTAL_COUNT           = 126 // 注册天数
	TASK_TYPE_DECOMPOSE_HEROS           = 127 // 分解英雄
	TASK_TYPE_HERO_STAR_POINT           = 128 // 英雄星级积分
	TASK_TYPE_LOGIN_DAY                 = 129 // 登录
	TASK_TYPE_IS_LOGIN                  = 130 // 是否成功登录
	TASK_TYPE_ASTROLOGY_COUNT           = 131 // 占星次数
	TASK_TYPE_ACTIVITY_LOGIN            = 133 // 活动表登录
	TASK_TYPE_SUMMON_ELITE_HEROS        = 141 // 召唤精英英雄
	TASK_TYPE_RECHARGE_ONCE             = 201 // 指定充值
	TASK_TYPE_RECHARGE_SINGLE           = 202 // 单笔充值
	TASK_TYPE_RECHARGE_MONEY_DAILY      = 203 // 每日累积充值
	TASK_TYPE_RECHARGE_COST             = 204 // 累积消耗
	TASK_TYPE_RECHARGE_EQUAL_SINGLE     = 205 // 单笔充值
	TASK_TYPE_RECHARGE_ALL              = 206 // 累积充值
	TASK_TYPE_JJC_SCORE                 = 212 // 竞技场积分
	TASK_TYPE_VIP_BUY                   = 213 // VIP等级
	TASK_TYPE_RECHARGE_GOLD_WEEK        = 214 // 黄金周卡
	TASK_TYPE_STAR_UP_COUNT_EQUAL       = 216 // 14的强版本
	TASK_TYPE_GET_HERO_WIDE             = 217 // 11的弱版本
	TASK_TYPE_REWARD_TASK_GET_EQUAL     = 218 // 102的强版本
	TASK_TYPE_INSTANCE_PROCESS          = 221 // 铸时星域副本
	TASK_TYPE_ACTIFACT_GET              = 222 // 获得神器
	TASK_TYPE_LIFETREE_MAIN_LEVEL       = 231 // 创世神木等级
	TASK_TYPE_LIFETREE_OTHER_LEVEL      = 232 // 创世神木分支职业
	TASK_TYPE_ITEM_GET_COUNT            = 241 // 获得指定道具
	TASK_TYPE_ACTIVITY_EXCHANGE         = 242 // 获得指定道具
	TASK_TYPE_INTERSTELLAR_NEBULA       = 251 // 星云完成
	TASK_TYPE_INTERSTELLAR_NEBULAWAR    = 252 // 星耀完成
	TASK_TYPE_NOBILITY_LEVEL            = 271 // 达到爵位
	TASK_TYPE_ACTIVITY_BOSS_HURT_SINGLE = 281 // 暗域入侵单次入侵
	TASK_TYPE_ACTIVITY_BOSS_HURT_ALL    = 282 // 暗域入侵累计伤害
	TASK_TYPE_ACTIVITY_BOSS_COUNT       = 283 // 暗域入侵挑战次数
	TASK_TYPE_LUCKY_FIND                = 284 // 福袋召唤次数
)

// 任务相关废弃
const (
	PlayerLvTask        = 1   // 玩家等级
	HeroOwnTask         = 6   // 拥有的英雄
	HeroStarLvTask      = 7   // 英雄升星
	PlayerFightTask     = 14  // 玩家战力
	BuyMoneyTask        = 24  // 招财
	FindTask            = 26  // 酒馆购买
	TitleTask           = 27  // 称号任务
	BuyEnergyTask       = 39  // 购买体力`
	ShopTask            = 40  // 商店任务
	FinishTask          = 41  // 领取任务奖励,可指定任务类型
	CostGemTask         = 42  // 元宝消耗
	CostEnergeTask      = 49  // 消耗道具
	GetPowerTime        = 56  // 按时间体力领取
	SummonHerosTask     = 59  // 召唤英雄
	RechargeGemTask     = 60  // 充值元宝
	LoginTotalTask      = 61  // 累计登录
	RechargeOnceTask    = 73  // 单笔充值
	FriendCount         = 86  // 好友数量
	LoginActTask        = 126 // 活动累计登录
	UnionCopyTask       = 137 // 军团副本
	BeautyAdvance       = 140 // 宝物进阶
	TreasureaAdvance    = 141 // 宝物进阶数量累加
	BeautySearch        = 143 // 圣物搜索
	LegendLevelTask     = 144 // 传说关卡通过
	ItemExchangeTask    = 147 // 道具兑换（限时打折）
	TrialTask           = 155 // 试炼
	TaskMilitary        = 156 // 军演
	SummonHorseTask     = 157 // 购买水晶
	DiscernHorse        = 158 // 召唤魔宠
	HaveHorseCount      = 159 // 拥有魔宠数量
	HaveRunesCount      = 160 // 拥有符文数量
	ChaseTitle          = 165 // 王权争夺
	BuySoldierTask      = 166 // 购买兵符
	ActShopTask         = 172 // 活动商店刷新
	ActEnergyTask       = 173 // 活动体力购买
	SmeltTask           = 176 // 冶炼
	TigerUpgradeTask    = 177 // 虎符精炼
	TigerOwnTask        = 178 // 拥有虎符
	DiscountTask        = 800 // 限时打折
	HeroUpStarNumTask   = 179 // 武将升星, 数量, 星级, done
	HeroUpStarTimesTask = 180 // 武将升星, 升星次数, done
	EquipUpNumTask      = 181 // 装备强化, 装备数量, 达标等级 done
	EquipUpTimesTask    = 182 // 装备强化, 强化次数 done
	OwnGemNumTask       = 183 // 拥有宝石数量, 宝石等级, 宝石类型[0任意类型] done
	EquipStarNumTask    = 184 // 装备附魔,装备数量,达标等级 done
	EquipStarTimesTask  = 185 // 装备附魔,附魔次数 done
	CommonLevelTask     = 186 // 普通副本, 通关次数, 关卡Id[0代表任意关卡] done
	EliteLevelTask      = 187 // 精英副本, 通关次数, 关卡Id[0代表任意关卡] done
	TeamLevelTask       = 188 // 组队副本, 通关次数, 关卡Id[0代表任意关卡] done
	GemLevelTask        = 189 // 宝石副本, 通关次数, 关卡Id[0代表任意关卡] done
	ExpetionTask        = 190 // 远征副本, 通关次数, 关卡Id[0代表任意关卡] done
	TechDoneTask        = 191 // 科技 完成次数 done
	LivenessTask        = 192 // 活跃度 完成次数 达标数值 done
	PvpTimesTask        = 193 // 竞技场 完成次数 达标排名 0代表任意排名 done
	PvpScoreTask        = 194 // 竞技场 累计积分 done
	TowerResetTask      = 195 // 爬塔 重置次数 done
	TowerWinTask        = 196 // 爬塔 通关次数 关卡 0代表任意关卡 done
	TowerWin2Task       = 197 // 爬塔 通关次数 精英关卡 0代表任意关卡 done
	HaveTechCount       = 200 // 符合需求的科技数量 done
	TalentTask          = 203 // 天赋任务  done
	EquipColorTask      = 205 // 装备品级  done
	SoldierColorTask    = 207 // 佣兵品级  done
	SoldierLvTask       = 208 // 佣兵等级  done
	KingTaskFinish      = 209 // 王国任务_小环 done
	KingTaskDone        = 210 // 王国任务整个任务 done
	HaveArmyCount       = 211 // 符合条件佣兵数量 佣兵等级 佣兵品质 done
	//HaveFlagCount        = 212 // 符合条件军旗数量 军旗等级 军旗品质 done
	//UnionDonation        = 215 // 军团捐献 捐献类型 done
	FriendGiftCount = 216 // 好友赠送 done
	ArmyFightCount  = 217 // 佣兵挑战 挑战类型 done
	//UnionBossCount       = 218 // 军团boss done
	CityAttackCount    = 219  // 城池入侵 类型 done
	BuySmeltCount      = 220  // 购买神殿祝福物品 done
	PvpRankNow         = 2220 // 斗技场排行 done
	TenTimesSearch     = 223  // 十连抽次数 召唤类型 done
	HaveBossCount      = 224  // 拥有巨兽 品质 done
	NobilityTask       = 228  // 爵位等级
	GetOnHookAwardTask = 229  // 领取挂机奖励
	HaveDinivityTask   = 230  // 拥有神格
	//AllDinivityTask      = 231 // 英雄神格
	//DreamLandLootTask    = 232 // 神格幻境探索
	DreamLandLootTenTask = 233 // 神格幻境探索十连抽
	DungeonSweep         = 234 // 地下城扫荡, 通关次数, 章节Id[0代表任意章节] done
	HeroStarPoint        = 300 // 英雄星级积分 done

)
